### ISSUE TITLE
ICON choice

### ISSUE THREAD

**Issue by RobertoCravallo** [alex-jung/ha-departures-card#11]
First of all, thank you for this very, very cool integration. My wife is starting a new job on Monday and will we taking the Tram into Mannheim.  Made her a nice "Fahrplan" with your exzellent integration.

![Image](https://github.com/user-attachments/assets/3f125eee-7c79-4adc-ac42-ed1ac16bcf15)

As she is only using a tram, the "bus" makes no sense here. I would prefer to use a tram icon. 

Would be nice if configurable.

**Comment by alex-jung** [comment]
Hello,

thank you ;) sure, this change was planed anyway and will be part of next release that is coming soon.

**Comment by alex-jung** [comment]
issue resolved in [Release 1.1.0](https://github.com/alex-jung/ha-departures-card/releases/tag/v1.1.0)

**Comment by RobertoCravallo** [comment]
![Image](https://github.com/user-attachments/assets/6cf3d657-8af5-40c2-974e-e587a5ace83d)

![Image](https://github.com/user-attachments/assets/9f0c6ba5-557a-4704-8a21-03e850ef2281)

Updated to 1.1.1, still getting the bus.

**Comment by alex-jung** [comment]
> ![Image](https://github.com/user-attachments/assets/6cf3d657-8af5-40c2-974e-e587a5ace83d)
> 
> ![Image](https://github.com/user-attachments/assets/9f0c6ba5-557a-4704-8a21-03e850ef2281)
> 
> Updated to 1.1.1, still getting the bus.

It looks like cache was not cleared. Did you cleared the cache? (Mostly close and open app again is enough)

**Comment by alex-jung** [comment]
> First thing I did was clearing the cache! Restarted HA a couple of times, still got the bus.

Strange, did you tried to "update info" or to "download again" in hacs?

**Comment by RobertoCravallo** [comment]
![Image](https://github.com/user-attachments/assets/a88dc5c0-bb14-49ab-a59d-7d3ace18b97e)

Uninstalled everything and reinstalled, working now. Question: Strange, two departures at the same time?

**Comment by alex-jung** [comment]
> ![Image](https://github.com/user-attachments/assets/a88dc5c0-bb14-49ab-a59d-7d3ace18b97e)
> 
> Uninstalled everything and reinstalled, working now. Question: Strange, two departures at the same time?

Did this issue occur one time / sporadically or is permanent?

**Comment by RobertoCravallo** [comment]
After manual refresh all icons where gone and where replaced by departure times.

**Comment by RobertoCravallo** [comment]
![Image](https://github.com/user-attachments/assets/de7e8213-a09d-4d62-bb95-48954d831c3e)

Some strange times in the list.

**Comment by alex-jung** [comment]
> ![Image](https://github.com/user-attachments/assets/de7e8213-a09d-4d62-bb95-48954d831c3e)
> 
> Some strange times in the list.
> 
> Went away, maybe due to deinstalling / reinstalling the integration? Don't know if you do any calculations with the times oder if they are from the external data provider. 

Yes, its very strange. Im doing not so much calculation with the times. Only calculate diff between both. Is the issue reproducible?

**Comment by RobertoCravallo** [comment]
I can't for the life of me figure out, how to configure this to show trams from "Mannheim, Theresienkrankenhaus" to  "Mannheim, Rheinau". All my tries are getting different values from the "Fahrplan".

**Comment by alex-jung** [comment]
Hab die Themen aufgeräumt, sonst werden hier zu viele Themen vermischt:
- two departures at the same time -> https://github.com/alex-jung/ha-departures-card/issues/14
- strange estimated time -> https://github.com/alex-jung/ha-departures-card/issues/15
- couple entities for the same line -> https://github.com/alex-jung/ha-departures/issues/69
